[pytest]
testpaths = tests
addopts = --browser chromium --headed --tracing retain-on-failure --screenshot only-on-failure --video retain-on-failure
markers =
    admin: testes que rodam logados como administrador
    aluno: testes que rodam logados como aluno
    marca_dagua: testes da feature de marca d'água
